version: '3'

services:
  db:
    build: db
    image: img_tkdw1_db
    container_name: cnt_tkdw1_db
    volumes:
      - vol_tkdw1_db_data:/var/lib/mysql
      - vol_tkdw1_db_socket:/db/socket
  app:
    build: app
    image: img_tkdw1_app
    container_name: cnt_tkdw1_app
    volumes:
      - vol_tkdw1_db_socket:/db/socket
      - vol_tkdw1_app_socket:/app/socket
    depends_on:
      - db
  nginx:
    build: nginx
    image: img_tkdw1_nginx
    container_name: cnt_tkdw1_nginx
    ports:
      - "80:80"
    volumes:
      - vol_tkdw1_app_socket:/app/socket
    depends_on:
      - db
      - app

volumes:
  vol_tkdw1_db_data:
    external: true
  vol_tkdw1_db_socket:
    external: true
  vol_tkdw1_app_socket:
    external: true
