version: '3'

services:
  db:
    build: db
    image: img_tkdw1_db
    container_name: cnt_tkdw1_db
    volumes:
      - vol_tkdw1_db_data:/var/lib/mysql
      - vol_tkdw1_db_socket:/db/socket
  webapp:
    build: webapp
    image: img_tkdw1_webapp
    container_name: cnt_tkdw1_webapp
    volumes:
      - vol_tkdw1_db_socket:/db/socket
      - vol_tkdw1_webapp_socket:/app/socket
    depends_on:
      - db
  nginx:
    build: nginx
    image: img_tkdw1_nginx
    container_name: cnt_tkdw1_nginx
    ports:
      - "80:80"
    volumes:
      - vol_tkdw1_webapp_socket:/app/socket
    depends_on:
      - db
      - webapp

volumes:
  vol_tkdw1_db_data:
    external: true
  vol_tkdw1_db_socket:
    external: true
  vol_tkdw1_webapp_socket:
    external: true
