version: "3"

services:
  webapp:
    build: .
    image: img_tkdw1_webapp
    container_name: cnt_tkdw1_webapp
    volumes:
      - vol_tkdw1_webapp_socket:/app/socket

volumes:
  vol_tkdw1_webapp_socket:
    external: true
