version: "3"

services:
  app:
    build: .
    image: img_tkdw1_app
    container_name: cnt_tkdw1_app
    volumes:
      - vol_tkdw1_app_socket:/app/socket

volumes:
  vol_tkdw1_app_socket:
    external: true
