version: "3"

services:
  nginx:
    build: .
    image: img_tkdw1_nginx
    container_name: cnt_tkdw1_nginx
    ports:
      - "80:80"
    volumes:
      - vol_tkdw1_app_socket:/app/socket

volumes:
  vol_tkdw1_app_socket:
    external: true
